config/routes.rb
Rails.application.routes.draw do
  devise_for :doctors, :controllers => {
  registrations: 'doctor/registrations'
  }
  devise_for :patients, :controllers => {
  registrations: 'patient/registrations'
  }
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'patients#index'
  resources :patients

end

app/models/patient.rb
class Patient < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :doctor
  validates :name, :notes, :age, :oxygenlevel, :doctor_id, presence: true
end

app/controllers/patient/confirmations_controller.rb
# frozen_string_literal: true

class Patient::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/patient/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Patient::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/patient/passwords_controller.rb
# frozen_string_literal: true

class Patient::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/patient/registrations_controller.rb
# frozen_string_literal: true

class Patient::RegistrationsController < Devise::RegistrationsController

  private
  def sign_up_params
    params.require(:patient).permit(:email, :password, :password_confirmation, :name, :notes, :age, :oxygenlevel, :doctor_id)
  end

  def account_update_params

  params.require(:user).permit(:name,  :email, :password, :password_confirmation, :current_password)

end


end

app/controllers/patient/sessions_controller.rb
# frozen_string_literal: true

class Patient::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/patient/unlocks_controller.rb
# frozen_string_literal: true

class Patient::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  before_action :find_patient, only: [:show, :edit, :update, :destroy]


  def index
    # @patients = Patient.all
  if params[:doctor].blank?
    @patients = Patient.all.order("created_at DESC")
    else
    @doctor_id = Doctor.find_by(name: params[:doctor]).id
    @patients = Patient.where(category_id: @doctor_id).order("created_at DESC")
    end
  end

  def show
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    respond_to do |format|
         if @patient.save
           format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
           format.json { render :show, status: :created, location: @patient }
         else
           format.html { render :new }
           format.json { render json: @patient.errors, status: :unprocessable_entity }
         end
       end
     end

  def edit
  end

  def update
    respond_to do |format|
      if @patient.update(post_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
      @patient.destroy
      respond_to do |format|
        format.html { redirect_to root_path, notice: 'Patient was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  

  private

  def patient_params
    params.require(:patient).permit(:name, :notes, :age, :oxygenlevel, :doctor_id)
  end


  def find_patient
    @patient = Patient.find(params[:id])
  end

end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
<div class = "form-group">
  <%= f.collection_select(:doctor_id, Doctor.all, :id, :name, {prompt: "Choose Doctor" }) %><br>
       <%= f.label :name %><br>
       <%= f.text_field :name, placeholder: "Enter patient name", class: 'form-control' %><br>
       <%= f.label :age %><br>
       <%= f.number_field :age %><br>
       <%= f.label :oxygenlevel %><br>
       <%= f.number_field :oxygenlevel, class: 'form-control' %><br>
       <%= f.label :notes %><br>
       <%= f.text_area :notes, placeholder: "Type the patient notes here", class: 'form-control' %><br>

       <%= f.submit 'Update Patient', class: 'btn btn-success'%>
   </div>
<% end %>

app/views/patients/edit.html.erb
<div class="container">
  <div class="page-header">
    <h1>Edit Patient</h1>
  </div>
</div>
<div class="container">
  <%= render 'form' %>
  <%= link_to 'Back', root_path, class: 'label label-primary' %>
</div>

app/views/patients/index.html.erb
<div class="container">
  <div class="page-header">
    <h1>Patients</h1>
  </div>
</div>
<div class="container">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Oxygen Level</th>
        <th>Content</th>
        <th>Age</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @patients.each do |patient| %>
        <tr>
          <td><%= link_to patient.name, patient%></td>
          <td><%= patient.notes %></td>
          <td><%= patient.age %></td>
          <td> --- </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/patients/new.html.erb
<h1>New Patient</h1>
<%= render 'form' %>
<%= link_to "Back", root_path, :class => "btn btn-primary btn-sm" %>

app/views/patients/show.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="panel-body">
      <h3><%= @patient.name %></h1>
      <h3><%= "Age: " + (@patient.age).to_s %></h2>
      <h3><%= "Oxygen Level: " + (@patient.oxygenlevel).to_s %></h2>

      <p>
        <br>
        <%= @patient.notes %>
        <br>

      </p>
    </div>

  </div>
  <%= link_to "Edit", edit_patient_path(@patient) %>
  <%= link_to "Delete", @patient, method: :delete, data: { confirm: "Are you sure?" }%>

</div>