config/routes.rb
Rails.application.routes.draw do
  devise_for :doctors, :controllers => {
  registrations: 'doctor/registrations'
  }
  devise_for :patients, :controllers => {
  registrations: 'patient/registrations'
  }
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'patients#index'
  resources :patients

end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-dark navbar-static-top navbar-expand-md">
    <div class="container">
        </button> <%= link_to "Patient Manager", root_path, class: 'navbar-brand' %>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav mr-auto">
            <% Doctor.all.each do |doctor| %>
            <li>
              <%= link_to doctor.name, patients_path(category: doctor.name) %>
            </li>
            <% end %>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">


    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <%= yield %>

  </body>
</html>

app/views/layouts/patient.html.erb
<% content_for :content do %>
    <div class="jumbotron text-center">
        <h1>Patients</h1>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <p>
                    <%= yield %>
                </p>
            </div>

        </div>
    </div>
    <% end %>
    <%= render template: "layouts/application" %>